spring:
  kafka:
    producer:
      properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        retries: 3
        acks: -1
    consumer:
      properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    properties:
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto.register.schemas: true
      processing.guarantee: exactly_once_v2
      state.dir: /tmp/kafka-streams
  cloud:
    function:
      definition: sourceProcessorPaymentEvents;sinkProcessorPaymentRecords;sinkProcessorNotifications
    stream:
      kafka:
        streams:
          binder:
            auto-create-topics: true
            configuration:
              default:
                key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            functions:
              sinkProcessorPaymentRecords:
                application-id: processor-payment-history-v1.0
              sinkProcessorNotifications:
                application-id: processor-notifications-v1.0

          bindings:
            sinkProcessorPaymentRecords-in-0:
              consumer:
                configuration:
                  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            sinkProcessorPaymentRecords-out-0:
              producer:
                configuration:
                  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

            sinkProcessorNotifications-in-0:
              consumer:
                configuration:
                  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            sinkProcessorNotifications-out-0:
              producer:
                configuration:
                  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

      bindings:
        # Our source processor, the only time we publish events
        sourceProcessorPaymentEvents-out-0:
          destination: payment-events
          content-type: application/*+avro
          producer:
            use-native-encoding: true
            partition-count: 2

        # The conversion of events to a state
        # The left part of the join is the event
        sinkProcessorPaymentRecords-in-0:
          destination: payment-events
          content-type: application/*+avro
          consumer:
            use-native-decoding: true
            concurrency: 2
        sinkProcessorPaymentRecords-out-0:
          destination: payment-history
          content-type: application/*+avro
          producer:
            use-native-encoding: true
            partition-count: 2

        # Webhook Notification async processor
        sinkProcessorNotifications-in-0:
          destination: payment-events
          content-type: application/*+avro
          consumer:
            use-native-decoding: true
            concurrency: 2
        sinkProcessorNotifications-out-0:
          destination: payment-events
          content-type: application/*+avro
          producer:
            use-native-encoding: true
            partition-count: 2

  docker:
    compose:
      file: .docker/dev-compose.yaml
      lifecycle-management: start_only
      enabled: false

logging:
  level:
    root: WARN
    org.apache: ERROR
    zip.meetup: INFO
server:
  port: 8085
